import { chromium, devices } from "playwright-core";
const exe = "/Users/brau/Library/Caches/ms-playwright/chromium-1243/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
const browser = await chromium.launch({ executablePath: exe });
const ctx = await browser.newContext(devices["iPhone 14"]);
const page = await ctx.newPage();
page.on("pageerror", e => console.log("pageerror:", e.message));
await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
await page.getByLabel("Open menu").tap(); await page.waitForTimeout(400);
await page.screenshot({ path: process.argv[2] + "/menu.png" });
await page.getByRole("link", { name: "Logistics" }).tap(); await page.waitForTimeout(900);
console.log("after menu link, scrollY:", await page.evaluate(() => Math.round(window.scrollY)), "menu open:", await page.getByLabel("Close menu").count());
await page.getByRole("button", { name: /Picks things up fast/ }).scrollIntoViewIfNeeded();
await page.waitForTimeout(800);
await page.getByRole("button", { name: /Picks things up fast/ }).tap(); await page.waitForTimeout(400);
console.log("dialog visible:", await page.getByRole("dialog").isVisible());
await page.screenshot({ path: process.argv[2] + "/popup.png" });
await page.keyboard.press("Escape"); await page.waitForTimeout(200);
console.log("dialog after escape:", await page.getByRole("dialog").count());
await page.locator("#book").scrollIntoViewIfNeeded(); await page.waitForTimeout(800);
console.log("submit before fill:", await page.getByRole("button", { name: "Submit" }).count());
await page.getByLabel("Parent's name").fill("A"); await page.getByLabel("Child's name").fill("B");
await page.getByLabel("Phone number").fill("1"); await page.getByLabel(/relevant background/).fill("x");
await page.waitForTimeout(200);
console.log("submit after fill:", await page.getByRole("button", { name: "Submit" }).count());
const url = page.url(); await page.getByRole("button", { name: "Submit" }).tap(); await page.waitForTimeout(300);
console.log("url unchanged after submit:", page.url() === url);
await page.screenshot({ path: process.argv[2] + "/form.png" });
await browser.close();
